services:
  stir:
    image: stir:latest
    build: .
    volumes:
      - ./models:/stir/models/:rw

  stir-gpu:
    image: stir:latest
    build:
      context: .
    volumes:
      - ./models:/stir/models/:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
