name: stir
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.7.9
  - ipython
  - cudatoolkit=10.2
  - torchvision==0.7.0
  - pytorch==1.6.0
  - pip
  - pip:
    - pytorch-crf==0.7.2
    - tqdm==4.55.1
    - grakel==0.1.8
    - rich==13.5.2
